name: Node.js CI with Jest for React/Typescript

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./flowershop-frontend/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }} and run Jest tests
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      working-directory: ./flowershop-frontend/
      run: |
        npm ci
        npm run build --if-present
        npm run test
        npm run coverage